package io.github.kakusuke.migraphe.cli.resolver;

import java.io.IOException;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.yaml.snakeyaml.DumperOptions;
import org.yaml.snakeyaml.Yaml;

/**
 * Writes a {@link LockFile} as YAML to a {@code migraphe.lock.yaml} file.
 *
 * <p>Emits a fixed "do not edit" header followed by block-style YAML containing the {@code
 * lockfile-version} and a {@code plugins} list, where each plugin records its flattened {@code
 * groupId:artifactId:version} coordinate, its {@code sha256} pin, and a nested {@code dependencies}
 * list. The output is round-trippable by {@link LockFileReader}.
 */
public final class LockFileWriter {

    /** Creates a new {@code LockFileWriter}. */
    public LockFileWriter() {}

    private static final String HEADER =
            """
            # This file is auto-generated by `migraphe pin`. DO NOT EDIT.
            # Commit this file to lock plugin versions and SHA-256 hashes.
            """;

    /**
     * Serializes the lockfile to the given path, overwriting any existing file.
     *
     * @param lockFilePath the path to write the {@code migraphe.lock.yaml} file to
     * @param lockFile the lockfile model to serialize
     * @throws IOException if the file cannot be written
     */
    public void write(Path lockFilePath, LockFile lockFile) throws IOException {
        Map<String, Object> root = new LinkedHashMap<>();
        root.put("lockfile-version", lockFile.version());
        root.put("plugins", toYamlList(lockFile.plugins()));

        DumperOptions options = new DumperOptions();
        options.setDefaultFlowStyle(DumperOptions.FlowStyle.BLOCK);
        options.setIndent(2);
        options.setPrettyFlow(true);
        Yaml yaml = new Yaml(options);

        try (Writer writer = Files.newBufferedWriter(lockFilePath, StandardCharsets.UTF_8)) {
            writer.write(HEADER);
            yaml.dump(root, writer);
        }
    }

    private static List<Map<String, Object>> toYamlList(List<LockedPlugin> plugins) {
        List<Map<String, Object>> result = new java.util.ArrayList<>();
        for (LockedPlugin plugin : plugins) {
            Map<String, Object> entry = new LinkedHashMap<>();
            entry.put("coordinate", formatCoordinate(plugin.coordinate()));
            entry.put("sha256", plugin.sha256());
            entry.put("dependencies", toDepList(plugin.dependencies()));
            result.add(entry);
        }
        return result;
    }

    private static List<Map<String, Object>> toDepList(List<LockedDependency> dependencies) {
        List<Map<String, Object>> result = new java.util.ArrayList<>();
        for (LockedDependency dep : dependencies) {
            Map<String, Object> entry = new LinkedHashMap<>();
            entry.put("coordinate", formatCoordinate(dep.coordinate()));
            entry.put("sha256", dep.sha256());
            result.add(entry);
        }
        return result;
    }

    private static String formatCoordinate(MavenArtifactCoordinate c) {
        return c.groupId() + ":" + c.artifactId() + ":" + c.version();
    }
}
