package io.github.kakusuke.migraphe.cli.resolver;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class LockFileWriterTest {

    @TempDir Path tempDir;

    private static final String SHA1 =
            "3a7f000000000000000000000000000000000000000000000000000000000e21";
    private static final String SHA2 =
            "8c2e000000000000000000000000000000000000000000000000000000004b91";

    @Test
    void writesLockFileWithHeaderComment() throws IOException {
        Path lock = tempDir.resolve("migraphe.lock.yaml");
        LockedDependency dep =
                new LockedDependency(MavenArtifactCoordinate.parse("org.example:lib:2.3"), SHA2);
        LockedPlugin plugin =
                new LockedPlugin(
                        MavenArtifactCoordinate.parse("io.example:plugin-a:1.0"),
                        "maven-central",
                        SHA1,
                        List.of(dep));
        LockFile lockFile = new LockFile(1, List.of(plugin));

        new LockFileWriter().write(lock, lockFile);

        String content = Files.readString(lock);
        assertThat(content).startsWith("# This file is auto-generated by");
        assertThat(content).contains("DO NOT EDIT");
        assertThat(content).contains("lockfile-version: 1");
        assertThat(content).contains("io.example:plugin-a:1.0");
        assertThat(content).contains("maven-central");
        assertThat(content).contains(SHA1);
        assertThat(content).contains("org.example:lib:2.3");
        assertThat(content).contains(SHA2);
    }

    @Test
    void roundTripsThroughReader() throws IOException {
        Path lock = tempDir.resolve("migraphe.lock.yaml");
        LockedDependency dep =
                new LockedDependency(MavenArtifactCoordinate.parse("org.example:lib:2.3"), SHA2);
        LockedPlugin plugin =
                new LockedPlugin(
                        MavenArtifactCoordinate.parse("io.example:plugin-a:1.0"),
                        "maven-central",
                        SHA1,
                        List.of(dep));
        LockFile original = new LockFile(1, List.of(plugin));

        new LockFileWriter().write(lock, original);
        LockFile reloaded = new LockFileReader().read(lock).orElseThrow();

        assertThat(reloaded).isEqualTo(original);
    }

    @Test
    void writesEmptyPluginsListAsEmptyArray() throws IOException {
        Path lock = tempDir.resolve("migraphe.lock.yaml");

        new LockFileWriter().write(lock, new LockFile(1, List.of()));

        LockFile reloaded = new LockFileReader().read(lock).orElseThrow();
        assertThat(reloaded.plugins()).isEmpty();
    }
}
